plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.learn'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

ext {
    mapstructVersion = "1.5.5.Final"
    langchainVersion = "1.11.0"
    lombokVersion = "1.18.30"
}

dependencies {

    // ===============================
    // Spring Boot
    // ===============================
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // ===============================
    // Documentation
    // ===============================
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'

    // ===============================
    // Database
    // ===============================
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.liquibase:liquibase-core'

    // ===============================
    // Lombok
    // ===============================
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // ===============================
    // MapStruct
    // ===============================
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    // ===============================
    // AI / LangChain4j
    // ===============================
    implementation "dev.langchain4j:langchain4j:${langchainVersion}"
    implementation "dev.langchain4j:langchain4j-core:${langchainVersion}"
    implementation "dev.langchain4j:langchain4j-open-ai:${langchainVersion}"
    implementation "dev.langchain4j:langchain4j-ollama:${langchainVersion}"
    implementation "dev.langchain4j:langchain4j-google-ai-gemini:${langchainVersion}"


    // Agentic (beta)
    implementation "dev.langchain4j:langchain4j-agentic:1.11.0-beta19"

    // ===============================
    // Tests
    // ===============================
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito:mockito-core:5.12.0'
}

tasks.named('test') {
    useJUnitPlatform()
}