CREATE TABLE product
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    min_stock_level INTEGER                                 NOT NULL,
    max_stock_level INTEGER                                 NOT NULL,
    current_stock   INTEGER                                 NOT NULL,
    obsolete        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE stock_movement
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    date_time  TIMESTAMP WITHOUT TIME ZONE,
    type       VARCHAR(255),
    product_id BIGINT,
    CONSTRAINT pk_stock_movement PRIMARY KEY (id)
);

ALTER TABLE stock_movement
    ADD CONSTRAINT FK_STOCK_MOVEMENT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);
